name: Project Apollo push build

on: [push]

jobs:
  build:
    name: Build on Ubuntu 16.04 with ${{ matrix.dotnet_version }}
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        dotnet: [ '2.2.103', '3.0.100', '3.1.100' ]

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core ${{ matrix.dotnet }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Build with dotnet ${{ matrix.dotnet }}
      run: dotnet build --configuration Release
